### PR TITLE
set default ForceAuth: false

### PR DESCRIPTION
**Pull request by codeNgamer**
For IDP's who dont assume ForceAuthn: false, set explicit attribute to false

### CODE REVIEW

**Comment by pdspicer** [comment]
SAML spec indicates this should default to false if not provided, BUT this would probably be a good option to include (as opposed to a fixed value). Would you mind amending your fix to include `forceAuthn` as an option that can be passed in via the constructor (and passed through to SAML)?

**Comment by cjbarth** [comment]
@codeNgamer Do you have any interest in finishing this up?

**Comment by codeNgamer** [comment]
Hey sorry, I've been swamped and haven't used this in a while but I think I can get this done this weekend. Sound good?

**Comment by cjbarth** [comment]
Sounds good to me. Also, I think the value might already be allowed to pass through, so that might be worth checking before writing code. Thanks for giving time to this even tough you haven't used this in a while.

**Comment by cjbarth** [comment]
@codeNgamer We will be releasing v3.x in the upcoming weeks. If you would like this included in that release, please address the latest comments and we'll get this landed.

**Comment by cjbarth** [comment]
Closing due to inactivity. Please reopen if you wish to pursue this further.

**Pull request closed without merging**
