### PR TITLE
SAML protocol (simple) extensions

### PR DESCRIPTION
**Pull request by upsidedownmind**
This pull added SAML protocol (simple) extensions
Changelog:
- Added SAML protocol (simple) extensions
- Added request parameters in authorization methods (for internal use)

### CODE REVIEW

**Comment by upsidedownmind** [comment]
fixed jshint errors

**Comment by pdspicer** [comment]
Extensions are a nice addition.. As far as the ability to use HTTP redirect binding to read a SAML response is concerned: am I missing something in terms of where `validateGetResponse` is defined?

**Comment by upsidedownmind** [comment]
Hi pdspicer,
I'm sorry, I don't understand your concern about "validateGetResponse" can you give me more details? tnks

**Comment by markstos** [comment]
I"m not sure what @pdspicer was referring to. `validateGetResponse` is defined right here: https://github.com/bergie/passport-saml/pull/147/files#diff-41fc97a3e28a2b6f8b5ec3bdae6130d5R623

**Comment by markstos** [comment]
This PR could use some clean-up. This commit is particularly confusing. The diff shows it replacing most of the code in the project:

https://github.com/bergie/passport-saml/pull/147/commits/f6926d66c23cfb1c8589736ea6e02637b9a11e46

It would also be nice of `git rebase -i` was used to merge all the jshint/gitignore commits, and squash the "BugFix" commit into whatever commit it's bug fixing. 

It's great that some tests were added, but documentation is also needed as well. As a reviewer, it's also helpful if links are provided to the parts of the SAML spec that are being implemented in a given PR.

**Comment by edevil** [comment]
@upsidedownmind ping

**Comment by markstos** [comment]
@edevil You are welcome to contribute the refinements yourself in a fork and submit a replacement PR.

**Comment by cjbarth** [comment]
@upsidedownmind @edevil We will be releasing v3.x in the upcoming weeks. If you would like this included in that release, please address the latest comments and we'll get this landed.

**Comment by cjbarth** [comment]
Closing due to inactivity. Please reopen if you wish to pursue this further.

**Pull request closed without merging**
