### PR TITLE
Add error for POST requests when req.body is undefined

### PR DESCRIPTION
**Pull request by jrop**
Addresses #128

Sorry it took me so long to create this.

### CODE REVIEW

**Comment by pdspicer** [comment]
I think the check needs to be modified a little bit to potentially avoid "cannot read property 'SAMLResponse' of undefined" errors. In addition I think the check as currently written will break the HTTP-POST binding on SAMLRequests

**Comment by markstos** [comment]
Also, please add automated test coverage for this. Further, the error message doesn't exactly match the behavior. The error says: "`req.body` undefined for POST request", but the check is not for this, but for `req.body.SAMLResponse`. It's possible `req.body.SAMLResponse` could be `undefined`, while `req.body` is still defined.

**Comment by cjbarth** [comment]
@jrop We will be releasing v3.x in the upcoming weeks. If you would like this included in that release, please address the latest comments and we'll get this landed.

**Comment by jrop** [comment]
@cjbarth I've since moved on from the job where I needed this, and will not get around to modifying this PR to address the comments.  😢

**Pull request closed without merging**
