### PR TITLE
Roll-up changelog entries for beta releases

### PR DESCRIPTION
**Pull request by cjbarth**
@markstos , this is a PR that addresses your concerns mentioned in https://github.com/node-saml/passport-saml/issues/839#issuecomment-1582933682. If we want any of the lines in this changelog altered, we just have to change the name of the PR and regenerate the changelog.

I can do this same thing with `node-saml` if we like it.

### CODE REVIEW

**Review by markstos — APPROVED** [review]
Thanks, Chris. Maybe during a beta cycle we want to break out the specific changes between betas, but now it does seem more useful to have all the 4.x changes bunched together. 

I updated a couple of PR titles for upgrading passport and node-saml to also add "see changelog for breaking changes". 

I had just tried to upgrade to passport 4.x myself and also got stung by breaking changes I missed until production. 🤦‍♂️ The challenge was the breaking changes were spread between passport and node-saml as well. And from reading the passport-saml change, the language of simply "update dependency" didn't convey the risk, because minor dependency updates happen all the change.

So I hope by adding PR titles like "update passport -- see changelog for breaking changes", that will help diligent upgraders find all the details they need for a smooth upgrade. 

I'll review the node-saml changelog now.

**Comment by cjbarth** [comment]
No worries. Once you have `passport-saml` adjusted to your liking, I'll update this PR and then go over to `node-saml` and do the same thing. We can iterate until you're happy. One of these days I should see if we can get a GitHub action to do that work...

**Comment by cjbarth** [comment]
I've made some updates @markstos . What do you think now?

**Review by markstos — APPROVED** [review]
Looks good! 
image

**Pull request merged**
