### PR TITLE
Private Certificate should be called Private Key

### PR DESCRIPTION
**Pull request by RyanCopley**
I could be wrong, but I have never heard of a private certificate before. This confused my team quite a bit and i think it would be useful to correct this. I'm not claiming this is the optimal implementation, but starting this conversation would be great.

### CODE REVIEW

**Comment by louielang** [comment]
I agree with Ryan. I was super confused when I started using passport-saml and I was struggeling with this. At least the docs should be updated so its clear what "privateCert" is really for.

**Comment by markstos** [comment]
@louielang a PR to improve the docs is welcome.

**Comment by cjbarth** [comment]
I was also confused when I started using this project, but I too am concerned about backward compatibility. Perhaps we can consider this a breaking change for v2?

**Comment by markstos** [comment]
@RyanCopley The way you've implemented this, it IS backwards compatible, so it doesn't require a major semver release. Would you be willing to update the patch to be compatible with our current TypeScript code and add some docs and test for it? 

This project is maintained by other users like you. It's unlikely anyone else is going to finilsh this feature for you if you want to see this happen.

**Comment by RyanCopley** [comment]
Oh man, I've already switched jobs and tech stacks entirely now :( It may be hard for me to find time to do this since I won't be given company time, and I don't have any projects that have this problem anymore.

**Comment by RyanCopley** [comment]
I'll try contacting my former employer and see if I can get them to take a look.

**Comment by alon85** [comment]
> I'll try contacting my former employer and see if I can get them to take a look.

Please review this updated PR: https://github.com/node-saml/passport-saml/pull/488

**Comment by markstos** [comment]
Closing in favor of #488

**Pull request closed without merging**
