### PR TITLE
Create of Code of Conduct

### PR DESCRIPTION
**Pull request by markstos**
This is the standard Code of Conduct that Github recommends and I endorse. It's based on this, which is in turn based on Mozilla policies.

https://www.contributor-covenant.org/version/2/0/code_of_conduct/

### CODE REVIEW

**Comment by cjbarth** [comment]
I like this idea. Do we also need some form about contributor licensing?

**Comment by markstos** [comment]
We don't need a CLA. Github Terms of Service include this:

> Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms. 

That's from: https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license

See also:

 * [Why CLAs aren't good for open source](https://opensource.com/article/19/2/cla-problems)
 * [Why you probably shouldn’t add a CLA to your open source project](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/)

**Review by cjbarth — APPROVED** [review]

**Comment by markstos** [comment]
@gugu Any comments before this is merged?

**Comment by gugu** [comment]
Fine for me

**Pull request merged**
