### PR TITLE
Fixing NameID value mapping

### LINKED ISSUE #245: attrValueMapper fails to parse complex AttributeValue tags
attrValueMapper function parse correctly this AttributeStatement:

`<saml2:Attribute FriendlyName="NAME" Name="urn:oid:x.x.x.x" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
  <saml2:AttributeValue>VALUE</saml2:AttributeValue>
</saml2:Attribute>`

but it fails with this kind of AttributeStatement:

`<saml2:Attribute FriendlyName="NAME" Name="urn:oid:x.x.x.x" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
<saml2:AttributeValue>
  <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="XXX" SPNameQualifier="XX">VALUE</saml2:NameID>
</saml2:AttributeValue>
</saml2:Attribute>`

### PR DESCRIPTION
**Pull request by vpalmisano**
Fixes #245

### CODE REVIEW

**Comment by markstos** [comment]
Thanks for the contribution. 

The patch needs automated test coverage to be accepted. You could break out `attrValueMapper` into it's own function and then unit test that.

**Comment by huntdm07** [comment]
I've just added a similar PR that might fix this.

**Comment by markstos** [comment]
For reference, the PR @huntdm07 is referring to is: https://github.com/bergie/passport-saml/pull/249

**Comment by vpalmisano** [comment]
Hi all,
with the latest changes, I added the possibility to define a custom ``attrValueMapper`` function. With no option set, the default function is used.

**Comment by cjbarth** [comment]
Since #427 and #245 are closed, should this be closed too @vpalmisano ?

**Pull request closed without merging**
