### PR TITLE
Update xml-encryption to v1.2.3

### PR DESCRIPTION
**Pull request by forty**
This update xmldom to a non vulnerable version.

### CODE REVIEW

**Comment by cjbarth** [comment]
@forty Did you see that this broke the build?

**Comment by forty** [comment]
@cjbarth Sorry, I have no idea, I cannot reproduce issue here :/ can you?

**Comment by forty** [comment]
@cjbarth hum, running `npm ls` it looks like I messed up the package-lock. I did run an `npm dedup` after my npm install, but I always does, and that usually doesn't cause any trouble :thinking: 

Another weird thing is that it also seems to be messed up on master, but that did no make the build fail :shrug: 

Do you want me to open a PR with a fresh package-lock, regenerated from a clean `npm install` ?

**Comment by cjbarth** [comment]
Let me have a closer look myself. Thanks for the research.

**Pull request merged**
